### ISSUE TITLE
Demo APP在4.4中一安装打开就报错了。

### ISSUE THREAD

**Issue by DearZack** [Nightonke/BoomMenu#1]
是什么原因，没有兼容到4.4吗？

**Comment by Nightonke** [comment]
Could you provide some log info?

**Comment by DearZack** [comment]
I just download this file in [fir](http://fir.im/tv85) and try to install in my phone which is 4.4,when i open it,then crashed.
i can't provide any log info

**Comment by Nightonke** [comment]
OK, I have fixed this problem. I would upload the new version in 5 minutes. Thanks for your reporting!

**Comment by Nightonke** [comment]
@DearZack Try again? If there are some some bugs, please let me know~ Thanks.

**Comment by DearZack** [comment]
It's OK!
