### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by Morgan1990** [Nightonke/BoomMenu#101]
The sample app only shows how to use this with a custom actionbar. How do i use the boom menu with a support toolbar( API 21 and above).

**Comment by Nightonke** [comment]
I've add an [example](https://github.com/Nightonke/BoomMenu/blob/master/app/src/main/java/com/nightonke/boommenusample/ToolBarActivity.java) of using BMB in toolbar from version 2.0.8.

**Comment by Morgan1990** [comment]
Ok thank you. I'm now able to add it there.
