### ISSUE TITLE
After being shown, how do you programmatically hide the buttons ?

### ISSUE THREAD

**Issue by stefanionescu** [Nightonke/BoomMenu#103]
Hey guys,

Can't really figure out how can I hide the buttons from code when they are already shown. Can you kindly give me a hint ?

Thanks !

**Comment by ziadkiwan** [comment]
do you mean bmb.reboom() ?

**Comment by Nightonke** [comment]
You can control BMB by this methods: [wiki](https://github.com/Nightonke/BoomMenu/wiki/Control-BMB).

**Comment by stefanionescu** [comment]
That was silly of me...yep, reboom did the trick. Thank you !
