### ISSUE TITLE
Import Library To Xamarin Android

### ISSUE THREAD

**Issue by iranidesign** [Nightonke/BoomMenu#104]
Hello 
I cant Import Your Library to Xamarin 
Problem Acceess Modifier 
![image](https://cloud.githubusercontent.com/assets/18347708/24082283/2002b00a-0cd8-11e7-9b53-777c2ecc9bf2.png)

**Comment by Nightonke** [comment]
It seems that you need to modify the access modifiers of some methods in BMB. Because not everyone needs import BMB to Xamarin, I suggest you to do this transformation yourself.
