### ISSUE TITLE
Menu Listener does not work

### ISSUE THREAD

**Issue by Traumhaftt** [Nightonke/BoomMenu#107]
First problem : I add Toast message into first boom button but when I press the button, nothing happen. I control them with index number. And when I debug it, the listener is not working.

Secondly, there is different account I sign in and in every account, the number of buttons is changing. There is maximum 5 buttons. In one fragment there is only one button but when I refresh the page, the button's text and image change, it opens the second image and text. It repeats itself. Note: I used BuilderManager class.
Thank u.

**Comment by Nightonke** [comment]
Could you provide some code? Thank you.

**Comment by Traumhaftt** [comment]
I fixed the problem :)
