### ISSUE TITLE
Change color of all boom-buttons

### ISSUE THREAD

**Issue by Traumhaftt** [Nightonke/BoomMenu#109]
I want to set different colors for boom-button. When press the button, its color will change. How can I do this? Thank u.

**Comment by Nightonke** [comment]
Check the [wiki](https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button). Use the following methods for builders:
```
// The color of boom-button when it is at normal-state.
.normalColor(Color.RED)

// The resource of color of boom-button when it is at normal-state.
.normalColorRes(R.color.red)

// The color of boom-button when it is at highlighted-state.
.highlightedColor(Color.BLUE)

// The resource of color of boom-button when it is at highlighted-state.
.highlightedColorRes(R.color.blue)

// The color of boom-button when it is at unable-state.
.unableColor(Color.BLACK)

// The resource of color of boom-button when it is at unable-state.
.unableColorRes(R.color.black)
```

**Comment by Traumhaftt** [comment]
I can't use them because I want to customize them. I need to use  .normalColor(Color.RED) in if check method. How can I do this?

**Comment by Nightonke** [comment]
This feature will be achieved in version 2.0.9 as soon as possible.

**Comment by Nightonke** [comment]
@Traumhaftt From version 2.0.9, you can change contents in BMB even after booming. Check [Wiki](https://github.com/Nightonke/BoomMenu/wiki/Change-Boom-Buttons-Dynamically) for more details.

**Comment by sohel2178** [comment]
Uhh , Got a Solution

**Comment by rakeshbaral92** [comment]
Hello Mr. Sohel. Can you please tell how you did it ?

**Comment by zmurodov** [comment]
How can i remove imageview in boom button
