### ISSUE TITLE
Set dots inside BoomMenu button invisible

### ISSUE THREAD

**Issue by Barthomeus** [Nightonke/BoomMenu#116]
Hi :) Is it possible to make BoomMenu button without dots inside - only color , or drawable ? When I set setPiecePlaceEnum as null or Unknow I'm getting an error. Thanks in advance for help :)

Btw - great library! Thanks for that.

**Comment by Nightonke** [comment]
Emmm... I didn't try this, but, how about set the radius of dots to zero?
```
bmb.setDotRadius(0);
```
Check [here](https://github.com/Nightonke/BoomMenu/wiki/Attributes-for-BMB-or-Pieces-on-BMB#for-pieces-on-bmb) for more information.

**Comment by Barthomeus** [comment]
Thats it! Thanks Mate! ;)

**Comment by ojarabo** [comment]
Just to let others know. With ham, you can change this by assigning 0 to bmb_hamWidth.
app:bmb_hamWidth="0dp"

**Comment by Nightonke** [comment]
Thanks, @ojarabo
