### ISSUE TITLE
There is posible to set others click event listeners like onLongClickListener on option item?

### ISSUE THREAD

**Issue by dengue8830** [Nightonke/BoomMenu#117]
Im working on an option in my bmb that allows the user to record a voice message like Whatsapp or Telegram, and i can't find the way to set listeners like onLongClickListener or onTouchListener on the bmb option item.

I know that this is a so specific need, so i understand if is no possible.

Great work with this project!

**Comment by Nightonke** [comment]
Emm... Maybe the `getBoomButton(int index)` method can help. [It](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/BoomMenuButton.java#L1178) helps to get the boom-button of BMB. Then you can set `onLongClickListener ` for the boom-buttons(notice that the boom-button may be null). But, maybe adding a `onLongClickListener ` will conflict the original listener inside boom-button, which means the click-event may be strange... I didn't try it, but I hope you can tell whether the conflict happens if you do so.

**Comment by dengue8830** [comment]
`getBoomButton(int index)` allways get me null, `getBoomButtons().size()` allways get zero, what i am doing wrong?

I have a fragment
> layout

`<com.nightonke.boommenu.BoomMenuButton
                android:id="@+id/bmb_opciones_programa"
                android:layout_width="0dp"
                android:layout_height="0dp"
                app:bmb_backgroundEffect="false"
                app:bmb_buttonEnum="ham"
                app:bmb_inFragment="true"/>`

> java

`private BoomMenuButton mOpcionesProgramaBmb;

@Override
    public View onCreateView...
        mOpcionesProgramaBmb = (BoomMenuButton) view.findViewById(R.id.bmb_opciones_programa);
        mOpcionesProgramaBmb.setPiecePlaceEnum(PiecePlaceEnum.HAM_1);
        mOpcionesProgramaBmb.setButtonPlaceEnum(ButtonPlaceEnum.HAM_1);
        mOpcionesProgramaBmb.addBuilder(new HamButton.Builder()
                .normalImageRes(R.drawable.ic_textsms_white_48dp)
                .normalColor(ContextCompat.getColor(getContext(), R.color.accent))
                .highlightedColor(ContextCompat.getColor(getContext(), R.color.accent))
                .normalText(getContext().getString(R.string.opcion_mensaje_programa_titulo))
                .subNormalText(getContext().getString(R.string.opcion_mensaje_programa_subtitulo)));

        Log.w("size", mOpcionesProgramaBmb.getBoomButtons().size()+"");// zero D: `

**Comment by Nightonke** [comment]
Because the boom-buttons are created when BMB is clicked. So I suggest you to use `getBoomButton(int index)` after the BMB is clicked. You can use the `OnBoomListener` to detect the will-boom event.

**Comment by dengue8830** [comment]
haa ok

i tried with the BoomButton, the event is triggered only if i touch in the margin of the item. So i thought to attach the event in the inner view, i tried with the childView of the BoomButton, but i have the same result. There is any way to get deeper child view's? Or may be is the BoomButton layout who is intercepting the event.

@Override
     public void onBoomDidShow...
                Log.e("size", mOpcionesProgramaBmb.getBoomButtons().size()+""); // 1
                Log.e("child count", bb.getChildCount()+""); // 1
                BoomButton bb = mOpcionesProgramaBmb.getBoomButton(0);
                View childView = bb.getChildAt(0);
                childView.setOnClickListener...

**Comment by Nightonke** [comment]
Yes, you can get the child views of a boom-button by its methods:
```
    /**
     * Get the image view of a boom button.
     *
     * @return image view
     */
    public ImageView getImageView() {
        return image;
    }

    /**
     * Get the text view of a boom button.
     *
     * @return text view
     */
    public TextView getTextView() {
        return text;
    }

    /**
     * Get the sub text view of a boom button.
     *
     * @return sub text view
     */
    public TextView getSubTextView() {
        return subText;
    }
```

**Comment by dengue8830** [comment]
yay, it works. But i have to attach the event to the three main components to give the experience of record a message touching the BoomButton

View.OnClickListener click = ...
BoomButton bb = mOpcionesProgramaBmb.getBoomButton(0);
View iv = bb.getImageView();
iv.setOnClickListener(click)
View tv = bb.getTextView();
tv.setOnClickListener(click);
View stv = bb.getSubTextView();
stv.setOnClickListener(click);

This will be enough for now, but if we could get access to the [layout field](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/BoomButtons/BoomButton.java#L144) we could attach the event to one single element.

Thanks bro, you rock

**Comment by Nightonke** [comment]
@dengue8830 
Since version 2.1.0, you can get the [layout field](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/BoomButtons/BoomButton.java#L144) by method `getLayout` of boom-button.

**Comment by dengue8830** [comment]
Awsome, great work with this release.
Thanks

**Comment by Gnanendra18** [comment]
Hi,
When I am trying to set listener on boombutton layout, it is giving null pointer exception. I didn't get what the problem is? Please explain.
@Override
            public void onBoomDidShow() {
                bmb.getBoomButton(0).getLayout().setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Toast.makeText(getApplicationContext(), "Hello", Toast.LENGTH_LONG).show();
                        //startActivity(new Intent());
                    }
                });
            }

**Comment by Nightonke** [comment]
Hey, @Gnanendra18 Could you please provide the crash-log? Thanks.

**Comment by hernanex3** [comment]
```
try {
     Field f = mMenuButton.getClass().getDeclaredField("button");
     f.setAccessible(true);
     FrameLayout buttonFrameLayout = (FrameLayout) f.get(mMenuButton);
     buttonFrameLayout.setOnClickListener(new View.OnClickListener() {
         @Override
         public void onClick(View view) {
             // CLICK EVENT HERE
         }
     });
 }catch(Exception e) {
     throw new RuntimeException(e);
 }
```
It works, but is very ugly, can you expose the `button` layout?

**Comment by Nightonke** [comment]
Hey, @hernanex3 . The `button` layout is exposed since version 2.1.1.
