### ISSUE TITLE
Reducing the size of menu items ui issue

### ISSUE THREAD

**Issue by HasanShaikh** [Nightonke/BoomMenu#120]
I have two menu items for my boom menu.

I want to have the size of menu items same as the size of boom fab menu.
so i added this to my code.
` for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {
            TextOutsideCircleButton.Builder builder = new TextOutsideCircleButton.Builder()
                    .normalImageRes(floatmenuImage.get(i))
                    .normalColor(ContextCompat.getColor(this,floatmenuColor.get(i)))
                    .normalTextColor(ContextCompat.getColor(this,R.color.intro_slide_black))
                    .buttonRadius(Util.dp2px(30))
                    .normalText(floatmenu.get(i));

            bmb.addBuilder(builder);
        }`
here buttonRadius(Util.dp2px(30))) reduces the size of menu item but the image inside it does not fit at the center 
![device-2017-05-23-100917](https://cloud.githubusercontent.com/assets/17041057/26338831/efdd59ce-3fa0-11e7-92c6-2147e5dc8a5b.png)

And i have given my menu items color as orange and green, so the fab menu dot takes the same two colors.
But i want the fab menu dot colors to be white keeping my menu item colors orange and green.
![device-2017-05-23-100649](https://cloud.githubusercontent.com/assets/17041057/26338848/1d679fbc-3fa1-11e7-95af-78cb42874a80.png)

Thanks

**Comment by Nightonke** [comment]
Emmm... If I didn't misunderstand, you are looking for method `imageRect`. Check [wiki](https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button#image) for more details.

**Comment by HasanShaikh** [comment]
@Nightonke thanks for your answer.
I tried using image rect but it is not working.
Can you please help me out in solving the ui issue as i have shown in the above image?
and also how to change the dot colors of fab button.

**Comment by Nightonke** [comment]
You can change the color of dot by `pieceColor` method of builder.
What did you mean 'not working' by `imageRect` method? Can I check the code where you use `imageRect`?

**Comment by HasanShaikh** [comment]
For my image ui issue in the above shown image.
you suggested me to check this na " Check [https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button#image](url) for more details."

but this is not solving my problem.
i have already pasted my code from which i am creating the menu items.

**Comment by Nightonke** [comment]
Could you send the image-resources to me for a test?

**Comment by HasanShaikh** [comment]
ya sure.
I am using same image for both the menu items.
![ic_home_proptype](https://cloud.githubusercontent.com/assets/17041057/26390541/a78ac33c-407c-11e7-8387-ecad03bb4fb5.png)

**Comment by Nightonke** [comment]
@HasanShaikh 
Hey, as I said, method `imageRect` of builder can solve this problem:
```
static SimpleCircleButton.Builder getSimpleCircleButtonBuilder() {
    return new SimpleCircleButton.Builder()
            .normalImageRes(R.drawable.test)
            .buttonRadius(Util.dp2px(30))
            .imageRect(new Rect(Util.dp2px(10), Util.dp2px(10), Util.dp2px(50), Util.dp2px(50)));
}
```
And the effect:
![](https://4.bp.blogspot.com/-UV1YtDO4Hqs/WSgbC_nLH0I/AAAAAAAAAPo/DOkJMxs3pnks4f7gXbosX8fBT4f-aCfEQCLcB/s1600/Screenshot_1495800470.png)

**Comment by HasanShaikh** [comment]
@Nightonke thank you so much its working fine now.
