### ISSUE TITLE
How can I customize the background color of each ham button boomed on screen?

### ISSUE THREAD

**Issue by varunsngl** [Nightonke/BoomMenu#123]
Hi,

First of all great thanks for such a beautiful and helping project on GitHub. But I want to customize it for my app. My app is not so much colorful and hence I want to change colors of each boom button on the screen but doesn't found how to do that. Can you please help me?

**Comment by Nightonke** [comment]
The [wiki of ham button](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button#button) will tell you how.

**Comment by varunsngl** [comment]
Got it. Thanks.
