### ISSUE TITLE
setBuilder() is invalid

### ISSUE THREAD

**Issue by elanpang** [Nightonke/BoomMenu#124]
I want to use setBuilder() to change the button title and icon, but it was invalid.

**Comment by Nightonke** [comment]
You don't need to use `setBuilder` method. I suggest you to use `getBuilder(int index)` method to get the builder of the boom-button that you wanna change. Then change the attribute directly. Check the [Wiki of Change Boom Buttons Dynamically](https://github.com/Nightonke/BoomMenu/wiki/Change-Boom-Buttons-Dynamically) for more information.

**Comment by elanpang** [comment]
3q
