### ISSUE TITLE
Remove on click effect 

### ISSUE THREAD

**Issue by ziadkiwan** [Nightonke/BoomMenu#128]
Hello is there a way to remove the on click material effect from a button in the ham in action bar?

**Comment by Nightonke** [comment]
Yep. Use `rippleEffect(false)` method of builders to do that. Check [Wiki](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button) for more information.

**Comment by ziadkiwan** [comment]
Owww i searched the wiki well and couldn't find it anyway thanks!

**Comment by yocheved-check-in** [comment]
did you found it?

**Comment by ziadkiwan** [comment]
yes it's clearly stated in the wiki :)
