### ISSUE TITLE
what could be causing this crash ?

### ISSUE THREAD

**Issue by ziadkiwan** [Nightonke/BoomMenu#129]
Hello Night! thanks for the great library!

i'm receiving a crash on my playstore crash report which is:

> 
> java.lang.RuntimeException: 
>   at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:71)
>   at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:27)
>   at com.nightonke.boommenu.BoomMenuButton.doLayoutJobs(BoomMenuButton.java:348)
>   at com.nightonke.boommenu.BoomMenuButton.access$600(BoomMenuButton.java:55)
>   at com.nightonke.boommenu.BoomMenuButton$8.run(BoomMenuButton.java:1016)
>   at android.os.Handler.handleCallback(Handler.java:751)
>   at android.os.Handler.dispatchMessage(Handler.java:95)
>   at android.os.Looper.loop(Looper.java:154)
>   at android.app.ActivityThread.main(ActivityThread.java:6682)
>   at java.lang.reflect.Method.invoke(Native Method:0)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

i am wondering if its a problem with my implementation of the library or its a problem with the library it self, thank you!

**Comment by Nightonke** [comment]
There should be a crash-tip from [ExceptionManager](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/ExceptionManager.java). Could you plz provide the whole report to me? Any runtime-exception from ExceptionManager means that BMB is used in a incorrect way.

**Comment by ziadkiwan** [comment]
i cannot reach the whole report I'm getting this stack trace it's provided from play store crash report center

**Comment by ziadkiwan** [comment]
this is the report details: 


Report timestamp

Yesterday, 6:31 PM

Application version

3

Android version

Android 7.0

Device
Galaxy S6 Edge (zerolte)

Manufacturer
    Samsung
RAM (MB)
    3072
Screen size
    1440 × 2560
Screen density (dpi)
    640
Native platform
    armeabi-v7a
OpenGL ES version
    3.1
CPU make
    Samsung
CPU model
    Exynos 7420

**Comment by ziadkiwan** [comment]
the strange thing is that it works on my device normally, it happens suddenly maybe ?

**Comment by Nightonke** [comment]
The crash threw from ExceptionManager means that BMB is used in a wrong rule. You can find all the reasons why the exception is threw in [ExceptionManager](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/ExceptionManager.java). For example, the number of pieces, boom-buttons and builders are not the same, like `The number of piece(3) is not equal to buttons'(4)`. Maybe, in some cases, the BMB is used in a wrong way in your App?

**Comment by ziadkiwan** [comment]
okay i will keep testing maybe i will find a way to reproduce the error on my actual device!, thanks!
