### ISSUE TITLE
背景问题

### ISSUE THREAD

**Issue by lvtanxi** [Nightonke/BoomMenu#13]
BoomMenuButton能不能设置一个drawable当作背景呢？

**Comment by Nightonke** [comment]
I didn't make this design. Because the small sub buttons are part of the background of the BMB. I have made a share design button just for sharing style. What kind of background do you want? Maybe I can make a new style.

**Comment by qssq** [comment]
我发现如果图标切大了 我把iamgebutton 设置为centercrop也是无效的结果是图标的布局定到了下面的文字下面来了。

**Comment by qssq** [comment]
您能不能打中文呀。
