### ISSUE TITLE
[Idea]lighter animation for old devices 

### ISSUE THREAD

**Issue by ziadkiwan** [Nightonke/BoomMenu#130]
Hello Nightonke, i know i'm asking much lately, but i'm working on a project hopefully if it works well i will include you github in the credits 👍  is there a way to make lighter animation for old devices like s4,s3 etc, like i will take care of detecting if the device is old, and then pass a flag in the constructor signaling the library to use lighter version? what do you think ?

**Comment by Nightonke** [comment]
Em..
Good suggestion. Currently BMB only provides a simple method to optimize the animation performance.
```
bmb.setFrames(40)
```
This can decrease the frames of the animations. Try this and if it does not work, let's consider other solutions.

**Comment by ziadkiwan** [comment]
Hello i tried it out on a Samsung S2 yeah it went much smoother!, i got a question out of the scope ever worked with value animators when resuming the animation on API < 19 using Va.start and setting the time the animation is restarting (it should continue) do you have any idea why ?
