### ISSUE TITLE
Re - Boom in onClick

### ISSUE THREAD

**Issue by noam2** [Nightonke/BoomMenu#131]
hello
i want bmb to re-boom immediately when a sub button is clicked, without hide animation, but if user presses background when bmb is open - it still should do the hiding animation 

how can i cancel the hiding animation of buttons only in OnClick method ?
thanks

**Comment by Nightonke** [comment]
In this situation, you can control BMB by yourself. First, you should set [auto-hide property](https://github.com/Nightonke/BoomMenu/wiki/Other-Animations-Attributes-for-Buttons#cancelable-and-auto-hide) to `false`. Then in OnClick method, [hide buttons without animations](https://github.com/Nightonke/BoomMenu/wiki/Control-BMB#control-bmb).

**Comment by noam2** [comment]
thanks .. works
