### ISSUE TITLE
fragment中 几个menu 没有 居中在下面那个浮动的按钮，能自定义下面浮动按钮大小不？

### ISSUE THREAD

**Issue by anjiao** [Nightonke/BoomMenu#18]
直接引用    compile 'com.nightonke:boommenu:1.0.9'

**Comment by ljf1172361058** [comment]
没有居中是因为初始化时BoomMenu需要准确测量(measure方法)出其的高宽,同时view绘制流程中的measure方法不会与activity或者fragment同步,所以直接在activity或者fragment的生命周期中初始化BoomMenuButton会造成爆炸原点始终在BoomMenuButton的左上方,在fragment你可以在BoomMenuButton.post(Runnable r)或者BoomMenuButton.postDelayed(Runnable r)中初始化BoomMenuButton

**Comment by Nightonke** [comment]
@anjiao Try the newest version for BMB. The bug is fixed.
