### ISSUE TITLE
排列出错，各个子项叠加在一起了。

### ISSUE THREAD

**Issue by mingzi12** [Nightonke/BoomMenu#2]
您好，不知道为什么点击BoomMenuButton显示各个子项时，每个子项都叠加在一起，而不是排列成3行3列(我设置的排列方式是3行3列)，求解。

**Comment by Nightonke** [comment]
Could u provide a picture of this bug and give me more information like the version of your phone and the code when you use it ?
Thanks for your reporting.

**Comment by mingzi12** [comment]
I add the BoomMenu in activity_mian.xml, and then initial the mBoommenuButton in the onCreate() method,and I use this code to initial the mBoommenuButton ( mBoomMenuButton.init(
                    drawables, // drawables[9] 
                    STRINGS,     // STRINGS[9]
                    colors,    // colors[9][2]
                    ButtonType.CIRCLE,     // 子按钮的类型
                    BoomType.PARABOLA_2,  // 爆炸类型
                    PlaceType.CIRCLE_3_3,  // 排列类型
                    null,               // 展开时子按钮移动的缓动函数类型
                    null,               // 展开时子按钮放大的缓动函数类型
                    null,               // 展开时子按钮旋转的缓动函数类型
                    null,               // 隐藏时子按钮移动的缓动函数类型
                    null,               // 隐藏时子按钮缩小的缓动函数类型
                    null,               // 隐藏时子按钮旋转的缓动函数类型
                    null                // 旋转角度
            )),thai is it. And my phone is MI3(Android 4.4),when I run the code in my phone,all nine items overlap together,I don't know why.

**Comment by Nightonke** [comment]
Oh, plz don't initialize in onCreate() method. You should do that in onWindowFocusChanged() method.

**Comment by mingzi12** [comment]
OK，I make  a mistake,but I didn't mean that,I ues this code ( mBoommenuButton = (BoomMenuButton)findViewById(R.id.boom)) in onCreate() ,and I actually use that code to initialize the mBoommenuButton in  onWindowFocusChanged();And now I have pushed my example to my github account,you can check it out here https://github.com/mingzi12/OneNote/blob/master/Boom.gif

**Comment by Nightonke** [comment]
OK, I've check your code. And I found that you make initialization in a loop like this:
```java
        for (int i = 0; i < 9; i++) {
            colors[i][1] = GetRandomColor();
            colors[i][0] = Util.getInstance().getPressedColor(colors[i][1]);

            boomMenuButton.init(
                    drawables, // drawables[9]
                    STRINGS,     // STRINGS[9]
                    colors,    // colors[9][2]
                    ButtonType.CIRCLE,     // 子按钮的类型
                    BoomType.PARABOLA_2,  // 爆炸类型
                    PlaceType.CIRCLE_3_3,  // 排列类型
                    null,               // 展开时子按钮移动的缓动函数类型
                    null,               // 展开时子按钮放大的缓动函数类型
                    null,               // 展开时子按钮旋转的缓动函数类型
                    null,               // 隐藏时子按钮移动的缓动函数类型
                    null,               // 隐藏时子按钮缩小的缓动函数类型
                    null,               // 隐藏时子按钮旋转的缓动函数类型
                    null                // 旋转角度
            );
        }
```
Please call init() just once.
If there are still something wrong, plz let me know that.

**Comment by mingzi12** [comment]
I have changed the code as what you said,but the same problem happens again,when I click the boombutton,all items overlap together.Could you please clone my demo to your computer and debug it,then show we what the problem?thank you for you help.these days I am doing my graduation project,and I think your project is very cool,so I want to use it in  my project.Thanks again.

**Comment by Nightonke** [comment]
OK, I would do that when I'm free these days. But, did you try the demo on your mobile and did the same bug happen again?

**Comment by mingzi12** [comment]
yes,absolutely,I change the code and build the project ,then run this demo not only in my phone but also in the genymotion,but the problem that I show you still happens again. I am sorry to trouble you,anyway thanks a lot.

**Comment by Nightonke** [comment]
@mingzi12 Hey, I have try my demo in android4.4.2 and MI3. But the demo runs perfectly. I suggest you check the [EasyUseActivity](https://github.com/Nightonke/BoomMenu/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fnightonke%2Fboommenusample%2FEasyUseActivity.java) and find whether there are mistakes in your code.

**Comment by mingzi12** [comment]
@Nightonke OK, I will check it.Thank you!
