### ISSUE TITLE
The image set on the BoomMenuButton has some problems

### ISSUE THREAD

**Issue by AD1024** [Nightonke/BoomMenu#20]
Just like the pic shows the Drawables I set on the buttons are odd....I tried to use high-resolution images to replace those images.But that didn't work.
<img width="425" alt="2016-05-18 2 36 17" src="https://cloud.githubusercontent.com/assets/12641212/15349539/318f584a-1d06-11e6-9340-b8ca53874160.png">

**Comment by Nightonke** [comment]
Hey, maybe you can use ```getImageViews()``` method to get all the imageviews on sub buttons and add some padding to make them look better. The source code of the method above is [here](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/BoomMenuButton.java#L1363).

**Comment by AD1024** [comment]
Thanks a lot,I'll try it later :p

**Comment by Nightonke** [comment]
Now you can set the image-rect and image-padding in the newest version. Please check the [wiki](https://github.com/Nightonke/BoomMenu/wiki) and find how to use it.
