### ISSUE TITLE
如果底部居中 根本没法用

### ISSUE THREAD

**Issue by qssq** [Nightonke/BoomMenu#25]
if gravity=center_h*\* not work 就根本没法用了，我们的项目就是需要做底部居中的这个问题怎么解决呢？ main_activity control 不过好像其他的可以我测试的是main_activity 的布局 ，

**Comment by qssq** [comment]
还真的是一个bug呀 - - 就是那个mainactivity那个布局添加水平居中那个动画就不能用了，还有您这个具体是咋实现的呀，看了半天代码没看懂原理，比如灰色的图层覆盖式怎么弄得呢。

**Comment by Nightonke** [comment]
The bug is fixed in the newest version. Thanks for feedback.
