### ISSUE TITLE
如果需要给那些弹出的 和 bootmmenu加上 小红点呢

### ISSUE THREAD

**Issue by qssq** [Nightonke/BoomMenu#26]
我们公司就有这样变态的需求了。。

**Comment by Nightonke** [comment]
Emm... I will consider add this function when I'm free. You can also read the source code and write this.

**Comment by qssq** [comment]
嗯，我真在这么做,您不是中国人呀 - -

**Comment by qssq** [comment]
ok

**Comment by Nightonke** [comment]
Now the code of newest version is easy to read(try your best). Maybe you can make a better RPBMB (Red Point Boom Menu Button) as your need.
