### ISSUE TITLE
一个严重的bug，不知道为啥

### ISSUE THREAD

**Issue by hiquanta** [Nightonke/BoomMenu#3]
添加如这个类库后Theme.AppCompat.Light.NoActionBar 无法隐藏Actionbar

**Comment by Nightonke** [comment]
I will check this tonight. That will be good and helpful if u can provide a picture about this code. Thanks for your reporting.

**Comment by Nightonke** [comment]
@hiquanta I didn't find any bugs about this. If you set the ```Theme.AppCompat.Light.NoActionBar``` of your activity, then you should NOT use boom menu button in action bar. Maybe you can show me your code.

**Comment by hiquanta** [comment]
I had solve it ，you are right，I use a base Theme in BaseActivity,Thank You

**Comment by Nightonke** [comment]
Nice.
