### ISSUE TITLE
How to change icon size

### ISSUE THREAD

**Issue by simonepopolizio-garoo** [Nightonke/BoomMenu#30]
When i put a drawable and i open the boom menu, the icons are too large hiding the label.

**Comment by simonepopolizio-garoo** [comment]
@Nightonke Any help?

**Comment by GPack1** [comment]
same to me

**Comment by Nightonke** [comment]
Sorry I'm too busy these days. I suggest you to change the size of the drawables to fit it, or if you have any solutions, please make pull-request. I will check this bugs as soon as possible.

**Comment by GPack1** [comment]
It is not really a bug: it works as `android:scaleType="fitXY"` works, that is scales the drawable to fit the ImageView. I tried to change the scaleType programmatically by `boomMenuButton.getImageViews()` but I get an Array of 4 null values.  
```
      // Now with Builder, you can init BMB more convenient
        new BoomMenuButton.Builder()
                .addSubButton(subButtonDrawables[0], subButtonColors[0], subButtonTexts[0])
                .addSubButton(subButtonDrawables[1], subButtonColors[1], subButtonTexts[1])
                .addSubButton(subButtonDrawables[2], subButtonColors[2], subButtonTexts[2])
                .addSubButton(subButtonDrawables[3], subButtonColors[3], subButtonTexts[3])
                .button(ButtonType.CIRCLE)
                .boom(BoomType.PARABOLA)
                .place(PlaceType.CIRCLE_4_1)
                .subButtonTextColor(ContextCompat.getColor(this, android.R.color.white))
                .subButtonsShadow(Util.getInstance().dp2px(2), Util.getInstance().dp2px(2))
                .init(boomMenuButton);

        ImageView[] subImageViews = boomMenuButton.getImageViews();
        Log.i("IMAGES", "-" + subImageViews.length);
        for (int i = 0; i < 4; i++) {
            if (subImageViews[i] != null)
            subImageViews[i].setScaleType(ImageView.ScaleType.CENTER);
        }
```

**Comment by GPack1** [comment]
@Nightonke  Pull request sent.

**Comment by Nightonke** [comment]
@GPack1 Thank you so much~

**Comment by simonepopolizio-garoo** [comment]
I changed my approach, so i won't it.
Is it resolved? should i close the issue?

**Comment by castrojr913** [comment]
The same issue. Some fork which fixes this bug?

**Comment by Nightonke** [comment]
@simonepopolizio-garoo @GPack1 @castrojr913 Now the new version provides methods to set image-frame and image-padding.

**Comment by imranali07** [comment]
I want to use icon size 56x56. Please help me how to fix icon size over boom menu button?

**Comment by bobby-walle** [comment]
private TextOutsideCircleButton.Builder buildMenuItem(@DrawableRes int iconResId, String text) {
            final int radius = ConvertUtils.dp2px(24);
            final int leftTop = radius / 2; //  radius * 2 / 4 
            final int rightBottom = radius * 3 / 2; // radius * 2 * 3 / 4
            return new TextOutsideCircleButton.Builder().normalImageRes(iconResId)
                                                        .buttonRadius(radius)
                                                        .imageRect(new Rect(leftTop,
                                                                            leftTop,
                                                                            rightBottom,
                                                                            rightBottom))
                                                        .normalText(text);
    }

fix menu icon size.

**Comment by AminEsmaeily** [comment]
**An easy solution.**
At first, our view is similar to below:
![image](https://user-images.githubusercontent.com/11803924/77887736-57a47f00-7280-11ea-8cee-6b75fe343801.png)

You can fix it using a wrapper drawable layout like this:
**drawable/ic_pantone_alt.xml**
``` xml
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_pantone"
        android:top="30dp" android:left="30dp"
        android:right="30dp" android:bottom="30dp"/>
</layer-list>
```

Then use the current resource as your image source file in code:
``` java
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.ic_pantone_alt));
```
Finally, the result is as follows:
![image](https://user-images.githubusercontent.com/11803924/77887826-7e62b580-7280-11ea-8a0f-7165dd8913e9.png)
