### ISSUE TITLE
不支持底部按钮的diy, 由于需求不同 我们的项目图标是自定义的而不是您给的这样

### ISSUE THREAD

**Issue by qssq** [Nightonke/BoomMenu#33]
所以我决定还是放弃使用你们的。写的太多太乱没法改了 特别是加上小红点这些需求一起的时候成本太高了

**Comment by juhuacha18** [comment]
这也开一个issue？？？issue是用来反馈问题的

**Comment by Nightonke** [comment]
@qssq Maybe you can check the newest version for your special need.
