### ISSUE TITLE
我觉得这个控件很多弊端,一点扩展性都没有

### ISSUE THREAD

**Issue by qssq** [Nightonke/BoomMenu#37]
就比如,实现格文本图片 的居中都这么难，布局里面是居中了，可是我怀疑画于圆角的算法不是这么弄的，怎么搞都是没法让蚊子和图片相对居中。      等于就是您一些限制了条条框框，想跳出去写 还不如自己写一个实现。

**Comment by qssq** [comment]
背景颜色怎么变得更灰色一点。 backgroundcolor是从黑色到输入的颜色 但是看到的是百分之20左右的灰色而已。现在打算把字弄到圆的下面了。但是白色的字得让 背景更灰色一点

**Comment by qssq** [comment]
发现弄到下面文字又不见了，我绝望了，控件真的不好用 只能做做demo  而已，上真实项目还差了档次，

**Comment by Nightonke** [comment]
Em... Yes, you're right. In fact, BMB is made when I learn android for several months. I will make it better these days.

**Comment by qssq** [comment]
原来我没有礼貌的说话,时候我发现我说错了。 就要是对于diy的改造我不知道咋弄了关于居中的问题是图片切得问题，但是设计图 是这样的背景是模糊的原背景,而那个弹出的菜单里面的文字则在圆菜单的下面，所以我不得不放弃您的牛逼控件了,
