### ISSUE TITLE
Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by zahansafallwa** [Nightonke/BoomMenu#40]
this error shown when trying to create boom menu by builder pattern on lollipop

**Comment by zahansafallwa** [comment]
I have added a solution in my fork of this repo and also sent pull request . Hope the owner will reply soon. Thanks

**Comment by arashmidos** [comment]
Same error. Any progress?

**Comment by Nightonke** [comment]
I will check whether the bug still exists in the newest version 2.0.1. Thanks for feedbacks.

**Comment by Nightonke** [comment]
@zahansafallwa This bug is fixed in version 2.0.2.
