### ISSUE TITLE
Boom GridView

### ISSUE THREAD

**Issue by DevendraSingh91** [Nightonke/BoomMenu#42]
Hi there,
I want to implement a gridview with boom effect. means all gridview items will be out from one icon when this icon will be burst. when app is opened.

**Comment by Nightonke** [comment]
I will provide a BMB-grid-view example in version 2.0.2.

**Comment by Nightonke** [comment]
@DevendraSingh91 Hey, I think I didn't understand your needs. Do you mean all the items of grid-view are the boom-buttons of BMB? This is not my plan of BMB and I may say I'm sorry...
