### ISSUE TITLE
Can't change subButton text color 

### ISSUE THREAD

**Issue by MohamedGamalFci** [Nightonke/BoomMenu#47]
I've tried a lot to change the subButton text color, and no hope !

**Comment by Ekeh** [comment]
I had the same issue and researched for many hours. I worked around it by passing the colors to ContextCompat.getColor() first before passing to subButtonColors array.
e.g
 int[][] subButtonColors=new int[][]{                    {ContextCompat.getColor(yourContext,R.color.grey),ContextCompat.getColor(yourContext, R.color.greyDark)}, {ContextCompat.getColor(yourContext,R.color.white),ContextCompat.getColor(yourContext, R.color.whiteDark)}} and so on. This resolved my issues.

**Comment by MohamedGamalFci** [comment]
I'm sorry, I ask mainly about sub button text color, can I change it ?

**Comment by Ekeh** [comment]
There is a method provided for that while using the Build. Though does not seen to work.
new BoomMenuButton.Builder()
.subButtonTextColor(Your color resource)

**Comment by MohamedGamalFci** [comment]
I already use it, but it doesn't work:
this is my code:
new BoomMenuButton.Builder()
                    .subButtons(drawables, colors, strings)
                    .button(ButtonType.HAM)
                    .boom(BoomType.LINE)
                    .place(PlaceType.HAM_3_1)
                    .subButtonsShadow(Util.getInstance().dp2px(2), Util.getInstance().dp2px(2))
                    .onSubButtonClick(this)
                    .dim(DimType.DIM_9)
                    .subButtonTextColor(ResourcesUtil.loadColorByResId(R.color.black))
                    .init(boomActionBarMenu);

**Comment by MohamedGamalFci** [comment]
subButtonTextColor is always white, and not changeable

**Comment by noam2** [comment]
yes it is changable ... i changed  it on toshow method in the listener

**Comment by halghzawi** [comment]
no one solve it ?

**Comment by noam2** [comment]
you have methods and listeners ...
In toShow() method you can get the textViews/ImageButtons and everything
and then change it.

**Comment by halghzawi** [comment]
@noam2  can you paste your code here it's doesn't work in my code

**Comment by noam2** [comment]
public void toShow() {

        TextView[] textViews = boomMenuToolBar.getTextViews();
        textViews[1].setTextColor(Color.RED);
        ImageView[] imageViews = boomMenuToolBar.getImageViews();
        for (int i = 0; i < imageViews.length; i++) {

            //   imageViews[i].setImageDrawable(getActivity().getResources().getDrawable(R.drawable.arrow));

            imageViews[i].getLayoutParams().height = 40;
            imageViews[i].getLayoutParams().width = 40;

        }
        imageViews[2].setPadding(100,0,0,0);
    }

    @Override
    public void showing(float fraction) {

    }

    @Override
    public void showed() {

    }

    @Override
    public void toHide() {

    }

    @Override
    public void hiding(float fraction) {

    }

    @Override
    public void hided() {
    }


here the code look mainly at the first method to show. i set also padding and image size there. it works perfectly

**Comment by Nightonke** [comment]
Hey guys, sorry for replying so late. Now in the newest version, we don't need to write the code so long. Because we can use builder to set attributes for boom-buttons. Please check [wiki](https://github.com/Nightonke/BoomMenu/wiki) to use.

**Comment by noam2** [comment]
hey ...
checked your new library - you are really talented , its an amazing library.
I have a question that i coudn't find a clarifacation about.
How do i add sub buttons to the BMB ?

i saw this :

for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {
    HamButton.Builder builder = new HamButton.Builder()
            .normalImageRes(R.drawable.butterfly)
            .normalTextRes("Butter Doesn't fly!")
            .subNormalTextRes("Little butter Doesn't fly, either!");
    bmb.addBuilder(builder);
}

is this the only way ? everytime i need to check i to know where i am

**Comment by noam2** [comment]
is there a way on ham button ,to put it as white color when its in action
bar, and to change its color when it opens/booms ?

**Comment by Nightonke** [comment]
1. You don't need to add sub-buttons to BMB. Just add builders then BMB will do adding jobs according to builders.
2. I'm considering add color-transaction animation in 2.0.2.

Thanks for suggestions.

**Comment by noam2** [comment]
its not color transaction. its just very common and nice to put a menu on
top which is white you know ? but if i do that it means the  sub buttons
should also be white and i dont want them to be white , i want them to be
regular colors.
when do you think you will publish version 2.0.2 ?

**Comment by noam2** [comment]
found a bug in the ham option.

**Comment by noam2** [comment]
i found another problem in the reboom method

**Comment by Nightonke** [comment]
@noam2 Now you can use different color for piece and button in version 2.0.2 with `builder.pieceColor(Color.WHITE)` method. And, what's the bugs you mentioned above?

**Comment by noam2** [comment]
there is a major problem with your 2.0.2 version. it throws
a java.lang.VerifyError: com/nightonke/boommenu/BoomButtons/BoomButton
execption every time button is pressed. it happend to me with 4.1 device ,
and i tested it a few times , rebuilding gradle and refreshing the library
a few times.

**Comment by Nightonke** [comment]
@noam2 Solved in version 2.0.3.

**Comment by noam2** [comment]
the things i was talking about earlier - i would suggest finding a smooth
solution when BMB is open , and the back button is pressed (it still stays
open).
also , when starting a new activity on subButton click there is a problem

**Comment by Nightonke** [comment]
Override onBackPressed method in activity to close BMB.

**Comment by noam2** [comment]
more important is when the sub button opens a new activity. it doesnt look
good or smooth , and its slow , the user can feel it stuck

**Comment by Nightonke** [comment]
@noam2 I make some tests to start a new activity by clicking sub button. But it seems smooth. I suggest you to use "Method Tracing" in android studio to find out the real reason of the slow-process. And now version 2.0.4 supports re-boom BMB by clicking back-button. Have a try!

**Comment by noam2** [comment]
Fragment and Activity ? because  i meant when pressed back on a fragment.
and also about the new activity , i meant that if sub button opens new
activity and re-booms at the same time it doesnt look good.

**Comment by Nightonke** [comment]
@noam2 I know what you're talking about.
1. "Pressed back" - Now version 2.0.4 supports press-back-to-re-boom.
2. "Doesn't look good" - I have tested this and I found it's smooth(looks good). And I suggest you to use "Method Tracing" in android studio to find out why it doesn't look good.

**Comment by noam2** [comment]
hey ,
do you know a good open source, android calendar library ? that can show
data on days ?

**Comment by noam2** [comment]
how did you make menu in white on action bar ? is shows me transparency
