### ISSUE TITLE
add video tutorials 

### ISSUE THREAD

**Issue by ziadkiwan** [Nightonke/BoomMenu#49]
Hello i was searching on you tube to find videos that state how to implement boom menu i couldn't find could you please add some it will be easier especially for boom in actionbar, thank you.

**Comment by ziadkiwan** [comment]
nvm i found https://www.youtube.com/watch?v=AAvvDySvJFc

**Comment by Nightonke** [comment]
That's nice! But I'm believe that now the newest version(from 2.0.0) is easier and more friendly to use. You can check [here](https://github.com/Nightonke/BoomMenu/wiki) for details.
