### ISSUE TITLE
how to set icon for the fab button itself

### ISSUE THREAD

**Issue by hisham2007** [Nightonke/BoomMenu#5]
Many thanks for great component. I am really exited about it but I have one issue:

I will use this component as a share fab. but from user point of view, there is no indicator that the button in bottom right of screen is used to share content. 

I have a suggestion ti give an option to set drawable for the fab button itself.

**Comment by Nightonke** [comment]
Emmm...
That would be a little hard because you know, the sub buttons are part of the "drawable" for the fab button. But I would try to add a special place type to act as "share drawable".
Thanks for reporting.

**Comment by Nightonke** [comment]
@hisham2007 Hey man, I have add a new style of BMB for a "share" fab button. Like this:
![Share](https://github.com/Nightonke/BoomMenu/blob/master/Pictures/show_share.gif?raw=true)
Check [this](https://github.com/Nightonke/BoomMenu#use-in-share-style) to use it. If there are any bugs(I haven't tested this new style), plz tell me.

**Comment by hisham2007** [comment]
Excellent job. it is far better than mine :)

May be the small tweak you can add when you are free: thickness of share lines and dots needs to be increased. it is very thin on my galaxy s6 running Android 5.1:
[http://i.imgur.com/Xs6nnca.png](url)

The original share icon:
[https://api.icons8.com/download/a5d38503865a8990ff38b46357345debdb740e3d/Android_L/PNG/256/Very_Basic/share-256.png](url)

**Comment by Nightonke** [comment]
Yep, I will make it better. And, your pictures are not-found.

**Comment by Nightonke** [comment]
Now the newest version 1.0.6 has corresponding methods to set the width and colors of the lines in share icon.
