### ISSUE TITLE
Sub Buttons Click Listener

### ISSUE THREAD

**Issue by recepysl** [Nightonke/BoomMenu#50]
i cant get the index Why?
boomMenuButton.setOnSubButtonClickListener(new BoomMenuButton.OnSubButtonClickListener() {
    @Override
    public void onClick(int buttonIndex) {
        // this code dosnt work for me 
    }
});

**Comment by mooniub428** [comment]
i am also facing this problem.

**Comment by mooniub428** [comment]
do you have a fixed this code?

**Comment by Nightonke** [comment]
Sorry for replying so late. Please check the newest version for bmb.

**Comment by Aditya-Sh** [comment]
I am having similar issue. I am trying to implement BoomMenuButton.OnSubButtonClickListener in an activity. But its not able to find OnSubButtonClickListener. Using version version 2.0.4
