### ISSUE TITLE
SubButton hidden in RecyclerView

### ISSUE THREAD

**Issue by fabricethilaw** [Nightonke/BoomMenu#53]
Hi Nightonke,

I am using  Boom Menu in a RecyclerView with three columns. Items in  the recyclerview are displayed like a gridview. And every time an item is clicked, a Boom Menu is shooted on the screen. 

Things go wrong only for items of the second column.  Unfortunately,,when the boom menu contains more than two sub buttons, some of them are not visible, or if there are, then their text disappears instantly.

**Comment by Nightonke** [comment]
@fabricethilaw Hey, the newest version of BMB is just updated. Please check whether the bug is fixed.
