### ISSUE TITLE
Fragment中没有onWindowFocusChanged方法，怎么做？

### ISSUE THREAD

**Issue by Hiboboo** [Nightonke/BoomMenu#54]
在Fragment中没有onWindowFocusChanged方法，虽然可以正常初始化，但BoomMenuButton中却失去了子按钮的色值排列，且爆炸原点始终在BoomMenuButton的左上方。
如果使用Activity中的onWindowFocusChanged方法在Fragment里回调，那View在什么地方初始化呢？
求方法破解

**Comment by ljf1172361058** [comment]
使用Activity中的onWindowFocusChanged方法是为了能够准确测量(measure方法)出BoomMenuButton的高宽,同时view绘制流程中的measure方法不会与activity或者fragment同步,所以你直接在activity或者fragment的生命周期中初始化BoomMenuButton会造成你说的爆炸原点始终在BoomMenuButton的左上方,在fragment你可以在BoomMenuButton.post(Runnable r)或者BoomMenuButton.postDelayed(Runnable r)中初始化BoomMenuButton

**Comment by Nightonke** [comment]
Hey, @Hiboboo @ljf1172361058 , now we don't need to write the silly code `onWindowFocusChanged `. Please check the [wiki](https://github.com/Nightonke/BoomMenu/wiki) for newest version. To use BMB in fragment, check [here](https://github.com/Nightonke/BoomMenu/wiki/Use-BMB-in-Fragment) for details.

**Comment by ljf1172361058** [comment]
@Nightonke  thanks.
Whether the same method in activty?

**Comment by Nightonke** [comment]
We don't need to find a same method  as `onWindowFocusChanged `. Just use builder can do everything well. Wiki can tell you how to do.

**Comment by ljf1172361058** [comment]
@ok,thanks
