### ISSUE TITLE
isOpen & dismiss

### ISSUE THREAD

**Issue by Kiarasht** [Nightonke/BoomMenu#59]
Is there an equivalent way to check with the new version? I can't seem to find one.

I like to override the back button to close the boom menu first before closing the app.

Thanks.

**Comment by Nightonke** [comment]
I will add these methods tonight. Thanks for the suggestion.

**Comment by Nightonke** [comment]
Hey, please check the [version 2.0.1](https://github.com/Nightonke/BoomMenu/wiki/Version-History) here to find the state-getter and other new attributes.

**Comment by Kiarasht** [comment]
Thank you.

**Comment by lucazin** [comment]
Did find the dismiss method.
I need check if boom is opened and if is.. dismiss

How can i do that?
thanks!
