### ISSUE TITLE
cannot set color

### ISSUE THREAD

**Issue by soheilghanbari1371** [Nightonke/BoomMenu#63]
hi i am using your perfect library
i got problem that when i use
 .normalColor(R.color.boom1)
  .normalTextColor(getcolorresource())

 these two line code for changing color of boom nothing happend an all color convert to black not those color which i defined please help me

**Comment by Nightonke** [comment]
Hey, the method's parameter is the value of color, not resource of color. I'm considering add.normalColorRes to the builder.

**Comment by Nightonke** [comment]
Methods to set color of text from resource are supported from version 2.0.9.
```
builder.highlightedTextColorRes(R.color.colorPrimary);
```
