### ISSUE TITLE
Different effects by the HamButton

### ISSUE THREAD

**Issue by zzh12138** [Nightonke/BoomMenu#65]
![image](https://cloud.githubusercontent.com/assets/16078807/21429818/6dd58d10-c89b-11e6-9b4c-2dbe59ee548a.png)
![s61222-230622](https://cloud.githubusercontent.com/assets/16078807/21430247/481adc90-c89d-11e6-89c2-6ee751ca0608.jpg)

I download the apk from here,but I got the different effects by using the HamButton.

Device : MEIZU MX3
Version:5.0.1

**Comment by Nightonke** [comment]
That's really strange... Maybe it's caused by the [Bottom Ham Button Top Margin](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button#the-special-boom-button) attribute. Try to change this attribute and check whether it's solved?
I don't have a MEIZU MX3 device to test it. Thanks for your feedback.

**Comment by zzh12138** [comment]
I set this attribute,it works.And I hop this bug could be fixed.

**Comment by Nightonke** [comment]
Have you tried other android-phones or simulators? I can not reappear this bug on other phones. I will try to borrow a MEIZU MX3 device in my company.

**Comment by zzh12138** [comment]
I use Redmi 3(MIUI 7.2) to test it.And the bug is exited.
Version 5.1.1

**Comment by zzh12138** [comment]
I have tried it in the virtual machine Nexus 5,which size is 720*1080:xhdpi and the problem still existed.You can try it and see this problem.

**Comment by Nightonke** [comment]
I will have a try when I'm off work tonight.

**Comment by Nightonke** [comment]
@zzh12138 Hey, try version 2.0.5 and check whether the bug exists.

**Comment by zzh12138** [comment]
The bug is fixed.Thanks

**Comment by Nightonke** [comment]
Nice.
