### ISSUE TITLE
can't show Menu 

### ISSUE THREAD

**Issue by OmarBenyahyaten** [Nightonke/BoomMenu#66]
I can't show the menu on SDK 17
i got this : 
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.nightonke.boommenu.BoomButtons.BoomButton.initCircleButtonDrawable

Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.nightonke.boommenu.BoomButtons.BoomButton.initHamButtonDrawable

**Comment by Nightonke** [comment]
Hey.

I have tested all-night-long but BMB works well in my SDK 17 device. But I found [this](https://github.com/prolificinteractive/material-calendarview/issues/147). Try to remove 'minifyEnabled true' or 'multiDexEnabled true' in your build.gradle file if there are.

**Comment by Nightonke** [comment]
No reply for this bug. I close it and if OmarBenyahyaten find that this bug still exists. Just open it.
