### ISSUE TITLE
No way to use padding, margins or height/width

### ISSUE THREAD

**Issue by kiaanpillay** [Nightonke/BoomMenu#68]
Hi,

I love the lib!!! Amazing stuff. I have an issue using the padding in the though, if I add any padding it just cuts that section off instead of shrinking the share icon. Same thing happens if I manually set the height or width for example it just crops the view basically instead of shrinking it. Is there anything I can do, otherwise I can't use the lib? Thank you so much!

**Comment by Nightonke** [comment]
Hey.

If I didn't misunderstand you, you can make paddings or small share icon as your need by this way:

![](https://4.bp.blogspot.com/-uvRlh3SH7o8/WF6CwMW4T-I/AAAAAAAAANU/rDGekcZB69M-b_LAV8XcXc9bflZ5V04bwCLcB/s1600/WechatIMG61.jpeg)

Of if you want to make it larger:

![](https://3.bp.blogspot.com/-fNTfytJGdRk/WF6CwZSo-2I/AAAAAAAAANY/hBO_PYGtOfEJy5nnMJVGHTAt_UeSHFZlwCLcB/s1600/WechatIMG62.jpeg)

For more information for custom BMB itself, check [here](https://github.com/Nightonke/BoomMenu/wiki/Attributes-for-BMB-or-Pieces-on-BMB).

**Comment by kiaanpillay** [comment]
Perfect! Thank you, my mistake
