### ISSUE TITLE
Sub Button Click Listener

### ISSUE THREAD

**Issue by Aditya-Sh** [Nightonke/BoomMenu#69]
I am trying to implement BoomMenuButton.OnSubButtonClickListener in an activity. But its not able to find OnSubButtonClickListener. Using version 2.0.4

**Comment by Nightonke** [comment]
Hey.
OnSubButtonClickListener is deleted in new version(2.0.0 and above). Try [this](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener).

**Comment by Aditya-Sh** [comment]
@Nightonke Thanks for the update. Can I implement it on an activity level.
Something like below?
`
public class MyActivity implements BoomMenuButton.OnBMClickListener {}
`

**Comment by Nightonke** [comment]
No, you cannot. If you want to use `Activity implements`, you have to use `Activity implements BoomMenuButton.OnBoomListener` but not `OnBMClickListener`.

**Comment by Aditya-Sh** [comment]
@Nightonke I'll try that.
Thank you for this great module.

**Comment by Aditya-Sh** [comment]
@Nightonke I am not able to reference `BoomMenuButton.OnBoomListener`, OnBoomListener method is not being referenced here. 

Also it seems that `TYPES` are removed in new version. I think there are new methods for old stuff I guess.

**Comment by Nightonke** [comment]
Yes, the new version changes lots of codes. Please read the [wiki for listener](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener) or the [example code](https://github.com/Nightonke/BoomMenu/blob/master/app/src/main/java/com/nightonke/boommenusample/ListenerActivity.java) for details.
