### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hisham2007** [Nightonke/BoomMenu#7]
My app is an Arabic app so I force RTL programmatically. When I used Share Fab, it had a strange UI. all dots stick to right of FAB.
It took me several hours to understand how it is drawn then I did some dirty workarounds to fix it in "placeDots()" method and "PlaceParamsFactory.getDotParams()" method

Note: 
I use this snippet to enforce RTL:

` try {
            String languageToLoad = "ar"; // your language
            Locale locale = new Locale(languageToLoad);
            Locale.setDefault(locale);
            Configuration config = activity.getResources().getConfiguration();
            //config.locale = locale;
            config.setLocale(locale);
            activity.getResources().updateConfiguration(config,
                    activity.getResources().getDisplayMetrics());
            activity.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        } catch (Exception ex){
            LogUtil.e(ex);
        }`

**Comment by Nightonke** [comment]
I will add a method to support RTL easily these days when I'm free. Thanks for reporting.

**Comment by Nightonke** [comment]
Hello @hisham2007 . Now BMB is able to support RTL. Please check [What's new in V1.0.7](https://github.com/Nightonke/BoomMenu#107).

**Comment by CaliRira** [comment]
Hi
My app is an persian app so I force RTL programmatically.
plase help me .
I use (Ham bmb) I cannot set default RTL (ham bmb) to all Language or RTL and LTR

**Comment by Nightonke** [comment]
You can adjust the position of text or image in ham button to support RTL. Check [Wiki](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button) and try `textRect`, `subTextRect` and `imageRect` methods.
