### ISSUE TITLE
How Do i set Icons/Text for Individual boom buttons

### ISSUE THREAD

**Issue by Edge-Developer** [Nightonke/BoomMenu#72]
I need help on how to set individual icons and text (for each boom button). please Help @Nightonke !

After I Initialized the Text_Inside_Circle_Button i wrote the code below:
```
`for (int i = 0; i<bmb.getPiecePlaceEnum().pieceNumber(); i++){
            TextInsideCircleButton.Builder builder = new
TextInsideCircleButton.Builder().normalImageRes(R.drawable.ic_content_copy).normalText("Copy")
                    .listener(new OnBMClickListener() {
                        @Override
                        public void onBoomButtonClick(int index) {
                            Toast.makeText(getContext(), "Clicked: "+index, Toast.LENGTH_LONG).show();
                        }
                    });

            builder.imagePadding(new Rect(10,10,10,10));
            bmb.addBuilder(builder);`
```

The Above Code only set one drawable image (and text) for all of the Boom Buttons.

How do i customise that?

**Comment by Nightonke** [comment]
All boom-buttons are set to one image, because you custom them in a loop...

... normalImageRes(R.drawable.image_1).normalText("Image 1")...
addBuilder(...)
... normalImageRes(R.drawable.image_2).normalText("Image 2")...
addBuilder(...)
... normalImageRes(R.drawable.image_3).normalText("Image 3")...
addBuilder(...)

Then you can custom boom-buttons in different style.

**Comment by Edge-Developer** [comment]
When i tried this:
```
for (int i = 0; i<bmb.getPiecePlaceEnum().pieceNumber(); i++){
            TextInsideCircleButton.Builder builder= new TextInsideCircleButton.Builder();
            builder.normalImageRes(R.drawable.ic_content_copy).normalText("Copy");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.drawable.ic_clear_black).normalText("Clear");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.drawable.ic_clear_black).normalText("Clear");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.mipmap.ic_launcher).normalText("Clear");
            bmb.addBuilder(builder);
            builder.listener(new OnBMClickListener() {
                @Override
                public void onBoomButtonClick(int index) {

                    switch (index) {
                        case 0:
                            ...
                            break;
                        case 1:
                            ...
                            break;
                        case 2:
                            ...
                            break;
                        case 3:
                            ...
                            break;
                    }
                }
            `});`
```
`I got the following error:

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: ng.pastquestions.testingit, PID: 5392
>                   java.lang.RuntimeException: Number of builders is not equal to buttons'!
>                       at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:55)
>                       at com.nightonke.boommenu.BoomMenuButton.doLayoutJobs(BoomMenuButton.java:345)
>                       at com.nightonke.boommenu.BoomMenuButton.access$500(BoomMenuButton.java:54)
>                       at com.nightonke.boommenu.BoomMenuButton$7.run(BoomMenuButton.java:994)
>                       at android.os.Handler.handleCallback(Handler.java:739)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                       at android.os.Looper.loop(Looper.java:148)
>                       at android.app.ActivityThread.main(ActivityThread.java:5417)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Edge-Developer** [comment]
# Also, when i tried this:

```
TextInsideCircleButton.Builder builder= new TextInsideCircleButton.Builder();
        builder.normalImageRes(R.drawable.ic_content_copy).normalText("Copy");
        bmb.addBuilder(builder);
        builder.normalImageRes(R.drawable.ic_clear_black).normalText("Clear");
        bmb.addBuilder(builder);
        builder.normalImageRes(R.drawable.ic_clear_black).normalText("Clear");
        bmb.addBuilder(builder);
        builder.normalImageRes(R.mipmap.ic_launcher).normalText("Clear");
        bmb.addBuilder(builder);

for (int i = 0; i<bmb.getPiecePlaceEnum().pieceNumber(); i++){
            builder.listener(new OnBMClickListener() {
                @Override
                public void onBoomButtonClick(int index) {

                    switch (index) {
                        case 0:
                            ...
                            break;
                        case 1:
                            ...
                            break;
                        case 2:
                            ...
                            break;
                        case 3:
                            ...
                            break;
                    }
                }
            `});`
```
**I did not Get an Error but:
1. I couldn't change the text
2. i couldn't change the icon (they all had the same icons)
3. all of the boom (sub menus) menu inherited the same colour**

**Comment by Nightonke** [comment]
...You didn't understand. One builder for one boom-button.

```
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.image1));
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.image2));
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.image3));
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.image4));
bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.image5));
```

**Comment by Edge-Developer** [comment]
Ok Got It! Thanks for Prompt Reply!


****another Issue*******
Whenever Battery saver mode is enabled the BOOM buttons stop working

**Comment by Nightonke** [comment]
I can't not find a method to keep animations

**Comment by Nightonke** [comment]
Now in version 2.0.7, BMB is able to work when battery saver mode is enabled.

**Comment by Hemen07** [comment]
@Edge-Developer : Did you solve it ?
        HamButton.Builder  builder=new HamButton.Builder();

        builder.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
        // bmb.addBuilder(builder);
        builder.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
        // bmb.addBuilder(builder);
        builder.normalImageRes(R.drawable.ic_cake_white_24dp).normalText("Csfsr");
        // bmb.addBuilder(builder);
        builder.normalImageRes(R.drawable.ic_keyboard_backspace_white_24px).normalText("Clear");
        // bmb.addBuilder(builder);

        for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {

            bmb.addBuilder(builder);
            builder.listener(new OnBMClickListener() {
                @Override
                public void onBoomButtonClick(int index) {

                }
            });
        }

**Comment by Nightonke** [comment]
@Hemen07 
One builder for on sub-button(called boom-button) in BMB. So try:
```
    builder.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
    bmb.addBuilder(builder);
    builder.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
    bmb.addBuilder(builder);
    builder.normalImageRes(R.drawable.ic_cake_white_24dp).normalText("Csfsr");
    bmb.addBuilder(builder);
    builder.normalImageRes(R.drawable.ic_keyboard_backspace_white_24px).normalText("Clear");
    bmb.addBuilder(builder);
    bmb.setOnBoomListener(new OnBoomListener() {
        @Override
        public void onClicked(int index, BoomButton boomButton) {
            // If you have implement listeners for boom-buttons in builders,
            // then you shouldn't add any listener here for duplicate callbacks.
        }
        @Override
        public void onBackgroundClick() {
            textViewForAnimation.setText("Click background!!!");
        }
        @Override
        public void onBoomWillHide() {
            Log.d("BMB", "onBoomWillHide: " + bmb.isBoomed() + " " + bmb.isReBoomed());
            textViewForAnimation.setText("Will RE-BOOM!!!");
        }
        @Override
        public void onBoomDidHide() {
            Log.d("BMB", "onBoomDidHide: " + bmb.isBoomed() + " " + bmb.isReBoomed());
            textViewForAnimation.setText("Did RE-BOOM!!!");
        }
        @Override
        public void onBoomWillShow() {
            Log.d("BMB", "onBoomWillShow: " + bmb.isBoomed() + " " + bmb.isReBoomed());
            textViewForAnimation.setText("Will BOOM!!!");
        }
        @Override
        public void onBoomDidShow() {
            Log.d("BMB", "onBoomDidShow: " + bmb.isBoomed() + " " + bmb.isReBoomed());
            textViewForAnimation.setText("Did BOOM!!!");
        }
    });
```

**Comment by Hemen07** [comment]
@Nightonke with for loop--Number of builders is not equal to buttons'! , got this, without for loop getting same text for all 4 views

**Comment by Nightonke** [comment]
That's because the 4 builders are the same instance. You have to create 4 instances of builders.
```
    newBuilder1.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
    bmb.addBuilder(newBuilder1);
    newBuilder2.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
    bmb.addBuilder(newBuilder2);
    ...
```

**Comment by Hemen07** [comment]
@Nightonke  Number of builders is not equal to buttons'! ,

 for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {
            HamButton.Builder builder = new HamButton.Builder();
            HamButton.Builder builder2 = new HamButton.Builder();
            HamButton.Builder builder3 = new HamButton.Builder();
            HamButton.Builder builder4 = new HamButton.Builder();


            builder.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
            bmb.addBuilder(builder);
            builder2.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
            bmb.addBuilder(builder2);



            builder3.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
            bmb.addBuilder(builder3);
            builder4.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
            bmb.addBuilder(builder4);
          /*  bmb.addBuilder(newBuilder2);
            builder.normalImageRes(R.drawable.ic_arrow_drop_down_circle_black_36dp).normalText("Copy");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.drawable.ic_account_circle_white_24dp).normalText("rdfdsf");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.drawable.ic_cake_white_24dp).normalText("Csfsr");
            bmb.addBuilder(builder);
            builder.normalImageRes(R.drawable.ic_keyboard_backspace_white_24px).normalText("Clear");
            bmb.addBuilder(builder);*/
            bmb.setOnBoomListener(new OnBoomListener() {
                @Override
                public void onClicked(int index, BoomButton boomButton) {
                    // If you have implement listeners for boom-buttons in builders,
                    // then you shouldn't add any listener here for duplicate callbacks.
                }

                @Override
                public void onBackgroundClick() {
                    // textViewForAnimation.setText("Click background!!!");
                }

                @Override
                public void onBoomWillHide() {
                    Log.d("BMB", "onBoomWillHide: " + bmb.isBoomed() + " " + bmb.isReBoomed());
                    // textViewForAnimation.setText("Will RE-BOOM!!!");
                }

                @Override
                public void onBoomDidHide() {
                    Log.d("BMB", "onBoomDidHide: " + bmb.isBoomed() + " " + bmb.isReBoomed());
                    // textViewForAnimation.setText("Did RE-BOOM!!!");
                }

                @Override
                public void onBoomWillShow() {
                    Log.d("BMB", "onBoomWillShow: " + bmb.isBoomed() + " " + bmb.isReBoomed());
                    // textViewForAnimation.setText("Will BOOM!!!");
                }

                @Override
                public void onBoomDidShow() {
                    Log.d("BMB", "onBoomDidShow: " + bmb.isBoomed() + " " + bmb.isReBoomed());
                    // textViewForAnimation.setText("Did BOOM!!!");
                }
            });
        }

//
    <com.nightonke.boommenu.BoomMenuButton
        android:id="@+id/bmb"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:bmb_buttonEnum="ham"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        app:bmb_piecePlaceEnum="piecePlace_ham_4"
        app:bmb_buttonPlaceEnum="buttonPlace_ham_4"
        />

**Comment by Nightonke** [comment]
Of course that error happens...
You create 4 builders in a loop. That, in fact, 4 * n builders are created.
Try my code above without a loop. I use loop in example just for simplifying codes. You must keep the number of builders same as the sub-buttons and pieces.

**Comment by Hemen07** [comment]
Yeah I forgot that tiny part, lot thanks bro

**Comment by japra2129** [comment]
Hi Bro..

I can't move to next activity with this codes 

`       bmb = (BoomMenuButton) findViewById(R.id.bmb);
        bmb.setButtonEnum(ButtonEnum.SimpleCircle);
        bmb.setPiecePlaceEnum(PiecePlaceEnum.DOT_6_2);
        bmb.setButtonPlaceEnum(ButtonPlaceEnum.SC_6_3);

        SimpleCircleButton.Builder builder = new SimpleCircleButton.Builder();
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.padi));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.sawit));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.jagung));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.bawang));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.kentang));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.cabai));


        for (int i = 0; i<bmb.getPiecePlaceEnum().pieceNumber(); i++) {


            builder.listener(new OnBMClickListener() {
                @Override
                public void onBoomButtonClick(int index) {

                    switch (index) {
                        case 0:
                            Intent padiIntent = new Intent(BrosurActivity.this,PadiActivity.class);
                            finish();
                            startActivity(padiIntent);
                        case 1:
                            Intent sawitIntent = new Intent(BrosurActivity.this,SawitActivity.class);
                            finish();
                            startActivity(sawitIntent);
                        case 2:
                            Intent jagungIntent = new Intent(BrosurActivity.this,JagungActivity.class);
                            finish();
                            startActivity(jagungIntent);
                        case 3:
                            Intent bawangIntent = new Intent(BrosurActivity.this,BawangActivity.class);
                            finish();
                            startActivity(bawangIntent);
                        case 4:
                            Intent kentangIntent = new Intent(BrosurActivity.this,KentangActivity.class);
                            finish();
                            startActivity(kentangIntent);
                        case 5:
                            Intent cabaiIntent = new Intent(BrosurActivity.this,CabaiActivity.class);
                            finish();
                            startActivity(cabaiIntent);
                    }
                }
            });

        }`

**Comment by ajaykeo123** [comment]
I am getting error for " textViewForAnimation.setText("Did RE-BOOM!!!");"

**Comment by Jardelpz** [comment]
Use um vetor

**Comment by arkochatterjee** [comment]
OnClickListener is not working when I am keeping every text and logo different by this

` bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Home"));
        bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Donor"));
        bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Recipient"));
        bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Search"));
        bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Transfer"));
        bmb.addBuilder(new TextInsideCircleButton.Builder().normalImageRes(R.drawable.logo).normalText("Blockchain"));


  for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {

            builder.listener(new OnBMClickListener() {
                @Override
                public void onBoomButtonClick(int index) {
                    // When the boom-button corresponding this builder is clicked.
                    Toast.makeText(MainActivity.this, "Clicked " + index, Toast.LENGTH_SHORT).show();
                }
            });
        }
      `
