### ISSUE TITLE
where can i find the code of  demo APK?

### ISSUE THREAD

**Issue by augepang** [Nightonke/BoomMenu#75]
Hi, where can i find the code of  demo APK? i need the code of  control example to reuse. thank you.

**Comment by Nightonke** [comment]
Control example? Find the [Control Wiki](https://github.com/Nightonke/BoomMenu/wiki/Control-BMB) or [code](https://github.com/Nightonke/BoomMenu/blob/master/app/src/main/java/com/nightonke/boommenusample/ControlActivity.java).
