### ISSUE TITLE
Change button color programatically

### ISSUE THREAD

**Issue by slormin** [Nightonke/BoomMenu#76]
Is there any way to change a button color once the builder is created for a button? Let's say you've got 3 buttons, and once the user clicks on one of them, the other 2 becomes in gray color.

**Comment by Nightonke** [comment]
There isn't currently. I will add this in next version.

**Comment by Nightonke** [comment]
Hey, when I 'm trying to add methods to change attributes of sub button, I found that they are all unsafe. For example, when the color of a sub button is changed, then the animation of changing color is unsafe. So these methods may not be added in new version expect I find some better way to solve the unsafe problem.

**Comment by Nightonke** [comment]
@slormin Hey, this feature is supported from version 2.0.9 now! Check [Wiki](https://github.com/Nightonke/BoomMenu/wiki/Change-Boom-Buttons-Dynamically) for more details.
