### ISSUE TITLE
How to resize sub button

### ISSUE THREAD

**Issue by j3p0n** [Nightonke/BoomMenu#77]
How to resize sub button cyrcle, its too big here.. ty sir
and how to set opacity of background overlay when boomed?

**Comment by Nightonke** [comment]
1. How to resize sub buttons?
Try `.buttonRadius` method for builder. Check [here](https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button) for more details. If you want to change the width or height for ham-button. Use `.buttonWidth` and `.buttonHeight` methods for builder. Here is the [wiki](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button).

2. Opacity of background?
I forget to add this in wiki. Thanks for reminding. Check [For Background Color When Booming](https://github.com/Nightonke/BoomMenu/wiki/Attributes-for-BMB-or-Pieces-on-BMB#for-background-color-when-booming).

**Comment by j3p0n** [comment]
ty sir for fast respons,, fixed
