### ISSUE TITLE
onBackPressed should close menu

### ISSUE THREAD

**Issue by kiaanpillay** [Nightonke/BoomMenu#78]
When onBackPressed is clicked and the menu is open it should close the menu to be consistent with Android Design Principles. Great lib though

**Comment by Nightonke** [comment]
Hey, BMB should have this attribute already. Check [this](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener#re-boom-bmb-when-back-button-is-clicked). The default value is true.
