### ISSUE TITLE
How to use it in Fragment?

### ISSUE THREAD

**Issue by focus2846** [Nightonke/BoomMenu#8]
I want to use in fragment ,and there is no onWindowFocusChanged method to override,so how to do it?

**Comment by Nightonke** [comment]
Maybe you can use a post method or use ViewTreeObserver. And also, you can use a interface in fragment to get the onWindowFocusChanged event in activity.
Check [this](http://stackoverflow.com/questions/30129984/how-to-get-the-onwindowfocuschanged-on-fragment).

**Comment by Nightonke** [comment]
Now you can use BMB in fragment with the newest version. Please check [wiki](https://github.com/Nightonke/BoomMenu/wiki/Use-BMB-in-Fragment) for details.
