### ISSUE TITLE
Set colour of ham menu to be constant

### ISSUE THREAD

**Issue by yagneshlp** [Nightonke/BoomMenu#80]
The colour of the Ham menu keeps changing randomly on every launch and also on rotation of device.
Is it possible to make this colour constant ? is this an enhancement like other issues related to colour?
and if i may, what is the ETA ?
Thanks in advance ;)

**Comment by Nightonke** [comment]
Of course you can set a color for a ham button as an constant. Please check the [wiki](https://github.com/Nightonke/BoomMenu/wiki/Ham-Button)  and try the .normalColor, .highlightColor methods.
