### ISSUE TITLE
Can't open boom programatically. Please tell what's wrong.

### ISSUE THREAD

**Issue by coolamz** [Nightonke/BoomMenu#83]
The app is crashing when I try to open boom programatically. Kindly check my code:

`        BoomMenuButton bmb = (BoomMenuButton) findViewById(R.id.bmb);

        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.inte));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.deri));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.trigo));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.abc));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.units));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.definte));
        bmb.addBuilder(new SimpleCircleButton.Builder().normalImageRes(R.drawable.geo));
        bmb.setShowDelay(0);
        bmb.setShowDuration(1000);
        bmb.setRotateDegree(1080);
        bmb.setHideDelay(0);
        bmb.setHideDuration(500);
        bmb.setFrames(80);
        bmb.boom();
        bmb.setOnBoomListener(new OnBoomListener() {
            @Override
            public void onClicked(int index, BoomButton boomButton) {
                if (index==1)
                {
                    Toast.makeText(MainActivity.this,"1",Toast.LENGTH_SHORT).show();
                }
            }

            @Override
            public void onBackgroundClick() {

            }

            @Override
            public void onBoomWillHide() {

            }

            @Override
            public void onBoomDidHide() {

            }

            @Override
            public void onBoomWillShow() {

            }

            @Override
            public void onBoomDidShow() {

            }
        });
//bmb.boom(); (Crashing after inserting here too)`

**Comment by Nightonke** [comment]
Don't try to use `.boom()` method in `onCreate` method, because some properties of BMB are not initialized.

**Comment by AsadAlihp** [comment]
How can I implement ```setOnBoomListener``` on ```getSquareTextInsideCircleButtonBuilder```,
I have tried this many times but failed -> 
``` bmb4 = (BoomMenuButton) findViewById(R.id.bmb4);
        assert bmb4 != null;
        for (int i = 0; i < bmb4.getPiecePlaceEnum().pieceNumber(); i++)
            bmb4.addBuilder(BuilderManager.getSquareTextInsideCircleButtonBuilder());
        bmb4.setOnBoomListener(new OnBoomListenerAdapter() {
            @Override
            public void onClicked(int index, BoomButton boomButton) {
                super.onClicked(index, boomButton);
                }
            }
        });

**Comment by AsadAlihp** [comment]
Also when I replace ```getSquareTextInsideCircleButtonBuilder``` with ```getHamButtonBuilder``` It works but not Square Text inside buttons. kindly guide ...
