### ISSUE TITLE
Unknown piece-place-enum!

### ISSUE THREAD

**Issue by Sekhtech** [Nightonke/BoomMenu#84]
Can you sir please tell me why this error occurs?

**Comment by hyd00** [comment]
I'm facing same error. How did you fix? please let me know. thanks

**Comment by Nightonke** [comment]
Maybe you didn't set the piece-place-enum attribute. Check [wiki](https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button) for details.
