### ISSUE TITLE
How can we use icons as we click it opens another activity

### ISSUE THREAD

**Issue by shubhamgcet** [Nightonke/BoomMenu#85]
I just want to  do that i want that if i click on the icons it should open another activity or links i tried to put setOnclickListener but it didn't do anything plz tell me how can i do that so that is can use in my project  @Nightonke

**Comment by aminebenemhamed** [comment]
Hi @shubhamgcet ,
After i tried i found the solution but in HamButtonActivity 
Try it, thank u

![try](https://cloud.githubusercontent.com/assets/24363293/22577435/93bbe076-e9b9-11e6-9949-f9098e88730b.PNG)

**Comment by Nightonke** [comment]
Don't try to use `onClickListener` directly. Check [Click Event and Listener](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener) to find out how to use.

**Comment by Nightonke** [comment]
@aminebenemhamed Thanks for your correct answer.

**Comment by aminebenemhamed** [comment]
Thanks, I tried to rename each button to its name, but I don't know how !


![16522407_1298189526917682_1347726906_o](https://cloud.githubusercontent.com/assets/24363293/22578180/ba23ef7e-e9be-11e6-9d32-9f50e196a1e2.png)

**Comment by Nightonke** [comment]
@aminebenemhamed Check #72 .
