### ISSUE TITLE
rename each button to its name

### ISSUE THREAD

**Issue by aminebenemhamed** [Nightonke/BoomMenu#87]
I tried to rename each button to its name, but I do not know how, 
Thank you 

``
        `for (int i = 0; i < bmb.getButtonPlaceEnum().buttonNumber(); i++) {
            bmb.addBuilder(new HamButton.Builder()
                    .normalImageRes(R.drawable.jellyfish)
                    .normalText("HOME ACTIVITY"));
}`
       
        
       

![16522407_1298189526917682_1347726906_o](https://cloud.githubusercontent.com/assets/24363293/22578327/c8d05656-e9bf-11e6-9e07-30e3567d8e5d.png)

**Comment by Nightonke** [comment]
Check #72.

**Comment by aminebenemhamed** [comment]
Thank you , resolved
