### ISSUE TITLE
Unknown Piece-Place-Enum!

### ISSUE THREAD

**Issue by Rumpel012** [Nightonke/BoomMenu#88]
Hey Nightonke, nice work on that menu - love it!

But I have a problem using a BoomMenuButton in a fragment. I can initiate it in the MainActivity where it works just fine. There is a ListView which is successfully filtered by clicking one of the MenuButtons. Afterwards the results are shown in an own fragment using the same layout as MainActivity (intention here is to make android's BackButton usable). The instantiated BoomMenuButton, amongst other member variables, is given to the constructor of that fragment so the reference can be set as an own member variable.

For a second the search results are shown as expected. But deflating the seperate MenuButtons, the app throws a fatal exception (unknown piece-place-enum!) and collapses. Seemingly, the piece-place-enum of the BoomMenuButton is no longer valid. Debugger showed me that its value (DOT_9_1) has in fact not changed at all...

xml:

`<com.nightonke.boommenu.BoomMenuButton
        android:id="@+id/bmb"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        app:bmb_normalColor="?android:attr/colorMultiSelectHighlight" />`

java in main:

`bmb = (BoomMenuButton) findViewById(R.id.bmb);
        bmb.setButtonEnum(ButtonEnum.TextInsideCircle);
        bmb.setPiecePlaceEnum(PiecePlaceEnum.DOT_9_1);
        bmb.setButtonPlaceEnum(ButtonPlaceEnum.SC_9_2);
        bmb.setBoomEnum(BoomEnum.PARABOLA_1);
        bmb.setShowMoveEaseEnum(EaseEnum.EaseInBounce);
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("notfall")
                .listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("notfall");
                        actionBar.setTitle(" DGS - notfall");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("mensch&tier").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("mensch&tier");
                        actionBar.setTitle(" DGS - mensch&tier");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("gefühle").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("gefühle");
                        actionBar.setTitle(" DGS - gefühle");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("beruf&verkehr").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("beruf&verkehr");
                        actionBar.setTitle(" DGS - beruf&verkehr");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("bildung").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("bildung");
                        actionBar.setTitle(" DGS - bildung");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("kommunikation").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("kommunikation");
                        actionBar.setTitle(" DGS - kommunikation");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("essen&trinken").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("essen&trinken");
                        actionBar.setTitle(" DGS - essen&trinken");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("geo").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("geo");
                        actionBar.setTitle(" DGS - geo");
                        runResult();
                    }
                }));
        bmb.addBuilder(new TextInsideCircleButton.Builder()
                .normalImageRes(R.drawable.abc_btn_check_to_on_mtrl_000)
                .normalText("basics").listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        gesturesAdapter.getCategoryFilter().filter("basics");
                        actionBar.setTitle(" DGS - basics");
                        runResult();
                    }
                }));`

running fragment constructor:
`    private void runResult() {
        resultFragment = ResultFragment.newInstance(
                getApplicationContext(),
                bmb,
                listView,
                gestureList,
                gesturesAdapter);
        getSupportFragmentManager().beginTransaction()
                .replace(R.id.activity_main, resultFragment)
                .addToBackStack(null)
                .commit();
    }`

java in fragment:
`    public static ResultFragment newInstance(
            Context ctxMain,
            BoomMenuButton bmbMain,
            ListView listViewMain,
            ArrayList<Gesture> gestureListMain,
            GesturesAdapter gesturesAdapterMain) {
        ResultFragment resultFragment = new ResultFragment();

        resultFragment.setCtx(ctxMain);
        resultFragment.setBmb(bmbMain);
        resultFragment.setListView(listViewMain);
        resultFragment.setGestureList(gestureListMain);
        resultFragment.setGesturesAdapter(gesturesAdapterMain);

        Bundle args = new Bundle();
        resultFragment.setArguments(args);
        return resultFragment;
    }`

**Comment by Rumpel012** [comment]
sorry for aligning... first try :S

**Comment by Rumpel012** [comment]
I overrode onBackPressed. Problem solved, unnessecary complication erased. Was not aware that it can be that simple - greetings from Oppenheimer ;)

**Comment by Nightonke** [comment]
😊
