### ISSUE TITLE
dimming screen background 

### ISSUE THREAD

**Issue by dariolr** [Nightonke/BoomMenu#89]
Great work, thank you!

How can I control the amount of obscuration of the screen on boom?

sorry for my english :)

**Comment by fabricethilaw** [comment]
I think you mean 'darkness' or 'opacity' :)

**Comment by dariolr** [comment]
exactly :)

**Comment by Farasy** [comment]
https://github.com/Nightonke/BoomMenu/wiki/Attributes-for-BMB-or-Pieces-on-BMB#for-background-color-when-booming

Set up your color in colors.xml as you prefer i.e. `#55AAAAAA` and use `app:bmb_dimColor="@color/colorname"`
