### ISSUE TITLE
recyclerview 中的应用问题

### ISSUE THREAD

**Issue by HUChengdu** [Nightonke/BoomMenu#9]
ListView如何知道是它的哪个item的subButton被点击了呢？需要知道对哪个item进行操作。

**Comment by Nightonke** [comment]
You can use an interface to finish this job. Just like put a button in every item of listview. Or check [this acticle](http://jmsliu.com/2444/click-button-in-listview-and-get-item-position.html) for help. I will add a sample in the next version of BMB. Thanks for reporting.
