### ISSUE TITLE
What are you doing?  

### ISSUE THREAD

**Issue by dinuscxj** [Nightonke/BoomMenu#91]
![image](https://cloud.githubusercontent.com/assets/14000274/23127161/eefc3dc4-f7b4-11e6-8a9f-835ab5deab84.png)

**Comment by Nightonke** [comment]
Ooops...
I'm testing a new application on osx, which do statistics of repositories for github user.
![](http://img.blog.csdn.net/20170220220029541?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMjkyNTAwOA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
