### ISSUE TITLE
how to run the button by code and not by icon

### ISSUE THREAD

**Issue by zeevchippc** [Nightonke/BoomMenu#94]
dear friend,

i want to set my onClickListener, that when it will fired, it will show the items.
how it can be achived?

**Comment by ziadkiwan** [comment]
use bmb.boom() after initializing the boom menu

**Comment by Nightonke** [comment]
Please check the [wiki](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener) for listener details.
