### ISSUE TITLE
Square buttons

### ISSUE THREAD

**Issue by Tansee** [Nightonke/BoomMenu#95]
Is it possible to let the buttons appear as squares instead of circles?

**Comment by Nightonke** [comment]
This feature has been supported from version 2.0.8. For documents, check below:
 [Square Simple Circle Button](https://github.com/Nightonke/BoomMenu/wiki/Simple-Circle-Button#square-button)  
 [Square Text Inside Circle Button](https://github.com/Nightonke/BoomMenu/wiki/Text-Inside-Circle-Button#square-button)  
 [Square Text Outside Button](https://github.com/Nightonke/BoomMenu/wiki/Text-Outside-Circle-Button#square-button)
