### ISSUE TITLE
Feature request: don't hide on background click

### ISSUE THREAD

**Issue by rostopira** [Nightonke/BoomMenu#96]
I'm not sure, if it is need an explanation
But I have an activity, which only has HamButtons and nothing else. I want to see animation of it appearing at start and that all. Click on buttons invokes certain activities or dialogs, but buttons must persist. I've set `bmb.isAutoHide = false` but click on background will leave user with beautiful but useless background image )=

**Comment by Nightonke** [comment]
I don't understand what you mean. Could you post some images about the bug you mentioned? Thank u.

**Comment by rostopira** [comment]
Activity opened, animation, boom
![screenshot_2017-02-25-17-27-21](https://cloud.githubusercontent.com/assets/16724952/23331916/6745252e-fb80-11e6-9693-aa8c9b30194b.png)
Reboom. Nothing.
![screenshot_2017-02-25-17-27-31](https://cloud.githubusercontent.com/assets/16724952/23331917/6745f468-fb80-11e6-9d99-8e211d041b04.png)

**Comment by Nightonke** [comment]
So what you want is that ham buttons still there after the background is clicked?

**Comment by rostopira** [comment]
Yeah, exactly

**Comment by Nightonke** [comment]
Try `setCancelable(false)` method. I think I forget to put this method in Wiki. Where did you find the usage of `AutoHide`?

**Comment by rostopira** [comment]
In autocomplete suggestions, probably, but I'm not sure, and it works well.
