### ISSUE TITLE
Lagging Recyclerview

### ISSUE THREAD

**Issue by Farasy** [Nightonke/BoomMenu#98]
Thanks for your awesome work!

May i miss something but when scrolling through my RecyclerView it lags while using `PiecePlaceEnum.DOT_5_4`.
The method for creating the `BoomMenuButton` is placed inside `onBindViewHolder()` therefore it get's called anytime when scrolling through the list. And each time calling `clearBuilders(), addBuilder() a.s.o` makes it lagging..

I'm quite sure i miss something 😅

**Comment by Nightonke** [comment]
I didn't get any lags when using `PiecePlaceEnum.DOT_5_4` in recycler-view...
Try to remove the BMB and test whether the lag still?

**Comment by Farasy** [comment]
Always done. Debugger was active 🤣
