### ISSUE TITLE
Is it possible to prevent buttons collapsing ?

### ISSUE THREAD

**Issue by stefanionescu** [Nightonke/BoomMenu#99]
Hey guys,

Kinda new here and verified the documentation but didn't find any way in which I can prevent the buttons going back after I press one. I kinda need them to stay on the screen. Can you help me with a tip ?

Thanks

**Comment by ziadkiwan** [comment]
you mean when you click on one you don't want it the boom menu to close ? there is something called bmb.autocancel(boolean) or bmb.autoclose(boolean) in the on create or when you first intialize the boom menu (just type auto and intelisense will help you),  if i'm not mistaken set it to false and then menu will not close, untill you use .reboom(), i hope that it helps!

**Comment by stefanionescu** [comment]
Thanks ziadkiwan ! That saved me
